version: 2

before:
  hooks:
    - go mod tidy
    - go mod vendor
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    binary: calsync
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -mod=vendor
    ldflags:
      - -s -w -X main.version={{.Tag}} -X main.commit={{.FullCommit}} -X main.date={{.Date}}

universal_binaries:
  - replace: true

brews:
  - name: calsync
    homepage: http://github.com/shadyabhi/calsync
    repository:
      owner: shadyabhi
      name: homebrew-tap
    dependencies:
      # Temporarily making this optional
      # - name: ical-buddy
    description: "Sync a local calendar to a remote Google Calendar"
    caveats: "For install instructions, visit: https://github.com/shadyabhi/calsync/wiki"
      
    commit_author:
      name: shadyabhi
      email: abhijeet.1989@gmail.com

checksum:
  name_template: 'checksums.txt'

archives:
  - formats: ['tar.gz']
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: ['zip']

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
