# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -coverprofile=./cover.out

    - name: go-test-coverage
      id: coverage
      uses: vladopajic/go-test-coverage@v2.7.1
      with:
        profile: cover.out

    - name: make coverage badge
      uses: action-badges/core@0.2.2
      if: contains(github.ref, 'main')
      with:
        label: coverage
        message: ${{ steps.coverage.outputs.badge-text }}
        message-color: ${{ steps.coverage.outputs.badge-color }}
        file-name: coverage.svg
        badge-branch: badges ## orphan branch where badge will be committed
        github-token: "${{ secrets.GITHUB_TOKEN }}"

